// flow-typed signature: 9783d249cfefa4735a650fbe26d371db
// flow-typed version: <<STUB>>/dialogflow_v^0.10.3/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dialogflow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dialogflow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dialogflow/src' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2/agents_client' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2/contexts_client' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2/doc/google/cloud/dialogflow/v2/doc_agent' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2/doc/google/cloud/dialogflow/v2/doc_audio_config' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2/doc/google/cloud/dialogflow/v2/doc_context' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2/doc/google/cloud/dialogflow/v2/doc_entity_type' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2/doc/google/cloud/dialogflow/v2/doc_intent' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2/doc/google/cloud/dialogflow/v2/doc_session_entity_type' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2/doc/google/cloud/dialogflow/v2/doc_session' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2/doc/google/longrunning/doc_operations' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2/doc/google/protobuf/doc_any' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2/doc/google/protobuf/doc_empty' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2/doc/google/protobuf/doc_field_mask' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2/doc/google/protobuf/doc_struct' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2/doc/google/rpc/doc_status' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2/doc/google/type/doc_latlng' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2/entity_types_client' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2/intents_client' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2/session_entity_types_client' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2/sessions_client' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2beta1/agents_client' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2beta1/contexts_client' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_agent' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_audio_config' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_context' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_document' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_entity_type' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_intent' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_knowledge_base' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_session_entity_type' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_session' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2beta1/doc/google/longrunning/doc_operations' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2beta1/doc/google/protobuf/doc_any' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2beta1/doc/google/protobuf/doc_empty' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2beta1/doc/google/protobuf/doc_field_mask' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2beta1/doc/google/protobuf/doc_struct' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2beta1/doc/google/rpc/doc_status' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2beta1/doc/google/type/doc_latlng' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2beta1/documents_client' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2beta1/entity_types_client' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2beta1' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2beta1/intents_client' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2beta1/knowledge_bases_client' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2beta1/session_entity_types_client' {
  declare module.exports: any;
}

declare module 'dialogflow/src/v2beta1/sessions_client' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dialogflow/src/index' {
  declare module.exports: $Exports<'dialogflow/src'>;
}
declare module 'dialogflow/src/index.js' {
  declare module.exports: $Exports<'dialogflow/src'>;
}
declare module 'dialogflow/src/v2/agents_client.js' {
  declare module.exports: $Exports<'dialogflow/src/v2/agents_client'>;
}
declare module 'dialogflow/src/v2/contexts_client.js' {
  declare module.exports: $Exports<'dialogflow/src/v2/contexts_client'>;
}
declare module 'dialogflow/src/v2/doc/google/cloud/dialogflow/v2/doc_agent.js' {
  declare module.exports: $Exports<'dialogflow/src/v2/doc/google/cloud/dialogflow/v2/doc_agent'>;
}
declare module 'dialogflow/src/v2/doc/google/cloud/dialogflow/v2/doc_audio_config.js' {
  declare module.exports: $Exports<'dialogflow/src/v2/doc/google/cloud/dialogflow/v2/doc_audio_config'>;
}
declare module 'dialogflow/src/v2/doc/google/cloud/dialogflow/v2/doc_context.js' {
  declare module.exports: $Exports<'dialogflow/src/v2/doc/google/cloud/dialogflow/v2/doc_context'>;
}
declare module 'dialogflow/src/v2/doc/google/cloud/dialogflow/v2/doc_entity_type.js' {
  declare module.exports: $Exports<'dialogflow/src/v2/doc/google/cloud/dialogflow/v2/doc_entity_type'>;
}
declare module 'dialogflow/src/v2/doc/google/cloud/dialogflow/v2/doc_intent.js' {
  declare module.exports: $Exports<'dialogflow/src/v2/doc/google/cloud/dialogflow/v2/doc_intent'>;
}
declare module 'dialogflow/src/v2/doc/google/cloud/dialogflow/v2/doc_session_entity_type.js' {
  declare module.exports: $Exports<'dialogflow/src/v2/doc/google/cloud/dialogflow/v2/doc_session_entity_type'>;
}
declare module 'dialogflow/src/v2/doc/google/cloud/dialogflow/v2/doc_session.js' {
  declare module.exports: $Exports<'dialogflow/src/v2/doc/google/cloud/dialogflow/v2/doc_session'>;
}
declare module 'dialogflow/src/v2/doc/google/longrunning/doc_operations.js' {
  declare module.exports: $Exports<'dialogflow/src/v2/doc/google/longrunning/doc_operations'>;
}
declare module 'dialogflow/src/v2/doc/google/protobuf/doc_any.js' {
  declare module.exports: $Exports<'dialogflow/src/v2/doc/google/protobuf/doc_any'>;
}
declare module 'dialogflow/src/v2/doc/google/protobuf/doc_empty.js' {
  declare module.exports: $Exports<'dialogflow/src/v2/doc/google/protobuf/doc_empty'>;
}
declare module 'dialogflow/src/v2/doc/google/protobuf/doc_field_mask.js' {
  declare module.exports: $Exports<'dialogflow/src/v2/doc/google/protobuf/doc_field_mask'>;
}
declare module 'dialogflow/src/v2/doc/google/protobuf/doc_struct.js' {
  declare module.exports: $Exports<'dialogflow/src/v2/doc/google/protobuf/doc_struct'>;
}
declare module 'dialogflow/src/v2/doc/google/rpc/doc_status.js' {
  declare module.exports: $Exports<'dialogflow/src/v2/doc/google/rpc/doc_status'>;
}
declare module 'dialogflow/src/v2/doc/google/type/doc_latlng.js' {
  declare module.exports: $Exports<'dialogflow/src/v2/doc/google/type/doc_latlng'>;
}
declare module 'dialogflow/src/v2/entity_types_client.js' {
  declare module.exports: $Exports<'dialogflow/src/v2/entity_types_client'>;
}
declare module 'dialogflow/src/v2/index' {
  declare module.exports: $Exports<'dialogflow/src/v2'>;
}
declare module 'dialogflow/src/v2/index.js' {
  declare module.exports: $Exports<'dialogflow/src/v2'>;
}
declare module 'dialogflow/src/v2/intents_client.js' {
  declare module.exports: $Exports<'dialogflow/src/v2/intents_client'>;
}
declare module 'dialogflow/src/v2/session_entity_types_client.js' {
  declare module.exports: $Exports<'dialogflow/src/v2/session_entity_types_client'>;
}
declare module 'dialogflow/src/v2/sessions_client.js' {
  declare module.exports: $Exports<'dialogflow/src/v2/sessions_client'>;
}
declare module 'dialogflow/src/v2beta1/agents_client.js' {
  declare module.exports: $Exports<'dialogflow/src/v2beta1/agents_client'>;
}
declare module 'dialogflow/src/v2beta1/contexts_client.js' {
  declare module.exports: $Exports<'dialogflow/src/v2beta1/contexts_client'>;
}
declare module 'dialogflow/src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_agent.js' {
  declare module.exports: $Exports<'dialogflow/src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_agent'>;
}
declare module 'dialogflow/src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_audio_config.js' {
  declare module.exports: $Exports<'dialogflow/src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_audio_config'>;
}
declare module 'dialogflow/src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_context.js' {
  declare module.exports: $Exports<'dialogflow/src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_context'>;
}
declare module 'dialogflow/src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_document.js' {
  declare module.exports: $Exports<'dialogflow/src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_document'>;
}
declare module 'dialogflow/src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_entity_type.js' {
  declare module.exports: $Exports<'dialogflow/src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_entity_type'>;
}
declare module 'dialogflow/src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_intent.js' {
  declare module.exports: $Exports<'dialogflow/src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_intent'>;
}
declare module 'dialogflow/src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_knowledge_base.js' {
  declare module.exports: $Exports<'dialogflow/src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_knowledge_base'>;
}
declare module 'dialogflow/src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_session_entity_type.js' {
  declare module.exports: $Exports<'dialogflow/src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_session_entity_type'>;
}
declare module 'dialogflow/src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_session.js' {
  declare module.exports: $Exports<'dialogflow/src/v2beta1/doc/google/cloud/dialogflow/v2beta1/doc_session'>;
}
declare module 'dialogflow/src/v2beta1/doc/google/longrunning/doc_operations.js' {
  declare module.exports: $Exports<'dialogflow/src/v2beta1/doc/google/longrunning/doc_operations'>;
}
declare module 'dialogflow/src/v2beta1/doc/google/protobuf/doc_any.js' {
  declare module.exports: $Exports<'dialogflow/src/v2beta1/doc/google/protobuf/doc_any'>;
}
declare module 'dialogflow/src/v2beta1/doc/google/protobuf/doc_empty.js' {
  declare module.exports: $Exports<'dialogflow/src/v2beta1/doc/google/protobuf/doc_empty'>;
}
declare module 'dialogflow/src/v2beta1/doc/google/protobuf/doc_field_mask.js' {
  declare module.exports: $Exports<'dialogflow/src/v2beta1/doc/google/protobuf/doc_field_mask'>;
}
declare module 'dialogflow/src/v2beta1/doc/google/protobuf/doc_struct.js' {
  declare module.exports: $Exports<'dialogflow/src/v2beta1/doc/google/protobuf/doc_struct'>;
}
declare module 'dialogflow/src/v2beta1/doc/google/rpc/doc_status.js' {
  declare module.exports: $Exports<'dialogflow/src/v2beta1/doc/google/rpc/doc_status'>;
}
declare module 'dialogflow/src/v2beta1/doc/google/type/doc_latlng.js' {
  declare module.exports: $Exports<'dialogflow/src/v2beta1/doc/google/type/doc_latlng'>;
}
declare module 'dialogflow/src/v2beta1/documents_client.js' {
  declare module.exports: $Exports<'dialogflow/src/v2beta1/documents_client'>;
}
declare module 'dialogflow/src/v2beta1/entity_types_client.js' {
  declare module.exports: $Exports<'dialogflow/src/v2beta1/entity_types_client'>;
}
declare module 'dialogflow/src/v2beta1/index' {
  declare module.exports: $Exports<'dialogflow/src/v2beta1'>;
}
declare module 'dialogflow/src/v2beta1/index.js' {
  declare module.exports: $Exports<'dialogflow/src/v2beta1'>;
}
declare module 'dialogflow/src/v2beta1/intents_client.js' {
  declare module.exports: $Exports<'dialogflow/src/v2beta1/intents_client'>;
}
declare module 'dialogflow/src/v2beta1/knowledge_bases_client.js' {
  declare module.exports: $Exports<'dialogflow/src/v2beta1/knowledge_bases_client'>;
}
declare module 'dialogflow/src/v2beta1/session_entity_types_client.js' {
  declare module.exports: $Exports<'dialogflow/src/v2beta1/session_entity_types_client'>;
}
declare module 'dialogflow/src/v2beta1/sessions_client.js' {
  declare module.exports: $Exports<'dialogflow/src/v2beta1/sessions_client'>;
}
